INSERT INTO COURSE(name) VALUES('JPA in 50 Steps');
INSERT INTO COURSE(name) VALUES('Angular Fundamentals');
INSERT INTO COURSE(name) VALUES('React Redux');
INSERT INTO COURSE(name) VALUES('Javascript - Understanding the Weird Parts');
INSERT INTO COURSE(name) VALUES('Vue - an Intro');
INSERT INTO COURSE(name) VALUES('Advanced Java');
INSERT INTO COURSE(name) VALUES('Eloquent Javascript');
INSERT INTO COURSE(name) VALUES('How to Win in the Stock Market');
INSERT INTO COURSE(name) VALUES('Understanding Backbone.js');
INSERT INTO COURSE(name) VALUES('Intermediate Spanish Speaking');
INSERT INTO COURSE(name) VALUES('API and Microservice Architecture');
INSERT INTO COURSE(name) VALUES('Spring Boot Fundamentals');
INSERT INTO COURSE(name) VALUES('Spring Deep Dive');
INSERT INTO COURSE(name) VALUES('Intro to Spring Data JPA');
INSERT INTO COURSE(name) VALUES('MEAN Stack Architecture');