INSERT INTO COURSE(name, created_date, last_updated_date) VALUES('JPA in 50 Steps', sysDate(), sysDate());
INSERT INTO COURSE(name, created_date, last_updated_date) VALUES('Angular Fundamentals', sysDate(), sysDate());
INSERT INTO COURSE(name, created_date, last_updated_date) VALUES('React Redux', sysDate(), sysDate());
INSERT INTO COURSE(name, created_date, last_updated_date) VALUES('Javascript - Understanding the Weird Parts', sysDate(), sysDate());
INSERT INTO COURSE(name, created_date, last_updated_date) VALUES('Vue - an Intro', sysDate(), sysDate());
INSERT INTO COURSE(name, created_date, last_updated_date) VALUES('Advanced Java', sysDate(), sysDate());
INSERT INTO COURSE(name, created_date, last_updated_date) VALUES('Eloquent Javascript', sysDate(), sysDate());
INSERT INTO COURSE(name, created_date, last_updated_date) VALUES('How to Win in the Stock Market', sysDate(), sysDate());
INSERT INTO COURSE(name, created_date, last_updated_date) VALUES('Understanding Backbone.js', sysDate(), sysDate());
INSERT INTO COURSE(name, created_date, last_updated_date) VALUES('Intermediate Spanish Speaking', sysDate(), sysDate());
INSERT INTO COURSE(name, created_date, last_updated_date) VALUES('API and Microservice Architecture', sysDate(), sysDate());
INSERT INTO COURSE(name, created_date, last_updated_date) VALUES('Spring Boot Fundamentals', sysDate(), sysDate());
INSERT INTO COURSE(name, created_date, last_updated_date) VALUES('Spring Deep Dive', sysDate(), sysDate());
INSERT INTO COURSE(name, created_date, last_updated_date) VALUES('Intro to Spring Data JPA', sysDate(), sysDate());
INSERT INTO COURSE(name, created_date, last_updated_date) VALUES('MEAN Stack Architecture', sysDate(), sysDate());